project_id = "wyutdvttldxkaqqysiuv"

[auth]
site_url = "https://login.qrcodevalidacao.com"
additional_redirect_urls = [
  "https://login.qrcodevalidacao.com/**",
  "https://regional.qrcodevalidacao.com/**",
  "https://estadual.qrcodevalidacao.com/**",
  "https://fornecedor.qrcodevalidacao.com/**",
  "https://transporte.qrcodevalidacao.com/**",
  "https://estoque.qrcodevalidacao.com/**",
  "https://municipal.qrcodevalidacao.com/**",
  "https://captacao.qrcodevalidacao.com/**",
  "https://mediumvioletred-penguin-501833.hostingersite.com/**",
  "http://localhost:5173/**",
]

[auth.email]
enable_signup = true
enable_confirmations = false
max_frequency = "1m"
otp_length = 8

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[functions.whatsapp-evolution]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.serper-places]
verify_jwt = true
