/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAcessosRouteImport } from './routes/_authenticated/acessos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAtendimentosRouteImport } from './routes/_authenticated/atendimentos'
import { Route as AuthenticatedAutenticidadeRouteImport } from './routes/_authenticated/autenticidade'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedCambioRouteImport } from './routes/_authenticated/cambio'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedContatosRouteImport } from './routes/_authenticated/contatos'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedDisparadorRouteImport } from './routes/_authenticated/disparador'
import { Route as AuthenticatedEntregasRouteImport } from './routes/_authenticated/entregas'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFornecedorRouteImport } from './routes/_authenticated/fornecedor'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedHierarquiaRouteImport } from './routes/_authenticated/hierarquia'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedInvestimentosRouteImport } from './routes/_authenticated/investimentos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedPromocoesRouteImport } from './routes/_authenticated/promocoes'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedScriptsRouteImport } from './routes/_authenticated/scripts'
import { Route as AuthenticatedSistemasDivisionaisRouteImport } from './routes/_authenticated/sistemas-divisionais'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedTrafegoPagoRouteImport } from './routes/_authenticated/trafego-pago'
import { Route as CatalogoSlugRouteImport } from './routes/catalogo.$slug'
import { Route as PedidoTokenRouteImport } from './routes/pedido.$token'
import { Route as ReciboTokenRouteImport } from './routes/recibo.$token'
import { Route as VerificarBatchIdRouteImport } from './routes/verificar.$batchId'
import { Route as AuthenticatedAtendimentosIndexRouteImport } from './routes/_authenticated/atendimentos.index'
import { Route as AuthenticatedAtendimentosContasRouteImport } from './routes/_authenticated/atendimentos.contas'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedConfirmarEntregaTokenRouteImport } from './routes/_authenticated/confirmar-entrega.$token'
import { Route as AuthenticatedContatosMapaRouteImport } from './routes/_authenticated/contatos_.mapa'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedCrmIdRouteImport } from './routes/_authenticated/crm.$id'
import { Route as AuthenticatedEquipeIndexRouteImport } from './routes/_authenticated/equipe.index'
import { Route as AuthenticatedEquipeIdRouteImport } from './routes/_authenticated/equipe.$id'
import { Route as AuthenticatedEquipeHierarquiaRouteImport } from './routes/_authenticated/equipe.hierarquia'
import { Route as AuthenticatedFornecedoresIndexRouteImport } from './routes/_authenticated/fornecedores.index'
import { Route as AuthenticatedFornecedoresIdRouteImport } from './routes/_authenticated/fornecedores.$id'
import { Route as AuthenticatedScriptsIdRouteImport } from './routes/_authenticated/scripts.$id'
import { Route as AuthenticatedTarefasIdRouteImport } from './routes/_authenticated/tarefas.$id'
import { Route as ApiDownloadPdfRouteImport } from './routes/api/download/pdf'
import { Route as ApiPublicDescadastroRouteImport } from './routes/api/public/descadastro'
import { Route as ApiPublicCampaignsWebhookRouteImport } from './routes/api/public/campaigns/webhook'
import { Route as ApiPublicEvolutionWebhookRouteImport } from './routes/api/public/evolution/webhook'
import { Route as ApiPublicGoogleCalendarCallbackRouteImport } from './routes/api/public/google-calendar/callback'
import { Route as ApiPublicMetaCallbackRouteImport } from './routes/api/public/meta/callback'
import { Route as ApiPublicMetaSyncRouteImport } from './routes/api/public/meta/sync'
import { Route as ApiPublicTrackingWebhookRouteImport } from './routes/api/public/tracking/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcessosRoute = AuthenticatedAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtendimentosRoute =
  AuthenticatedAtendimentosRouteImport.update({
    id: '/atendimentos',
    path: '/atendimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutenticidadeRoute =
  AuthenticatedAutenticidadeRouteImport.update({
    id: '/autenticidade',
    path: '/autenticidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCambioRoute = AuthenticatedCambioRouteImport.update({
  id: '/cambio',
  path: '/cambio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContatosRoute = AuthenticatedContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisparadorRoute = AuthenticatedDisparadorRouteImport.update({
  id: '/disparador',
  path: '/disparador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEntregasRoute = AuthenticatedEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedorRoute = AuthenticatedFornecedorRouteImport.update({
  id: '/fornecedor',
  path: '/fornecedor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHierarquiaRoute = AuthenticatedHierarquiaRouteImport.update({
  id: '/hierarquia',
  path: '/hierarquia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestimentosRoute =
  AuthenticatedInvestimentosRouteImport.update({
    id: '/investimentos',
    path: '/investimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromocoesRoute = AuthenticatedPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScriptsRoute = AuthenticatedScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSistemasDivisionaisRoute =
  AuthenticatedSistemasDivisionaisRouteImport.update({
    id: '/sistemas-divisionais',
    path: '/sistemas-divisionais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrafegoPagoRoute =
  AuthenticatedTrafegoPagoRouteImport.update({
    id: '/trafego-pago',
    path: '/trafego-pago',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const CatalogoSlugRoute = CatalogoSlugRouteImport.update({
  id: '/catalogo/$slug',
  path: '/catalogo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoTokenRoute = PedidoTokenRouteImport.update({
  id: '/pedido/$token',
  path: '/pedido/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ReciboTokenRoute = ReciboTokenRouteImport.update({
  id: '/recibo/$token',
  path: '/recibo/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificarBatchIdRoute = VerificarBatchIdRouteImport.update({
  id: '/verificar/$batchId',
  path: '/verificar/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtendimentosIndexRoute =
  AuthenticatedAtendimentosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAtendimentosRoute,
  } as any)
const AuthenticatedAtendimentosContasRoute =
  AuthenticatedAtendimentosContasRouteImport.update({
    id: '/contas',
    path: '/contas',
    getParentRoute: () => AuthenticatedAtendimentosRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)
const AuthenticatedConfirmarEntregaTokenRoute =
  AuthenticatedConfirmarEntregaTokenRouteImport.update({
    id: '/confirmar-entrega/$token',
    path: '/confirmar-entrega/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContatosMapaRoute =
  AuthenticatedContatosMapaRouteImport.update({
    id: '/contatos_/mapa',
    path: '/contatos/mapa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmIdRoute = AuthenticatedCrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedEquipeIndexRoute =
  AuthenticatedEquipeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEquipeRoute,
  } as any)
const AuthenticatedEquipeIdRoute = AuthenticatedEquipeIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEquipeRoute,
} as any)
const AuthenticatedEquipeHierarquiaRoute =
  AuthenticatedEquipeHierarquiaRouteImport.update({
    id: '/hierarquia',
    path: '/hierarquia',
    getParentRoute: () => AuthenticatedEquipeRoute,
  } as any)
const AuthenticatedFornecedoresIndexRoute =
  AuthenticatedFornecedoresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFornecedoresRoute,
  } as any)
const AuthenticatedFornecedoresIdRoute =
  AuthenticatedFornecedoresIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFornecedoresRoute,
  } as any)
const AuthenticatedScriptsIdRoute = AuthenticatedScriptsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedScriptsRoute,
} as any)
const AuthenticatedTarefasIdRoute = AuthenticatedTarefasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedTarefasRoute,
} as any)
const ApiDownloadPdfRoute = ApiDownloadPdfRouteImport.update({
  id: '/api/download/pdf',
  path: '/api/download/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDescadastroRoute = ApiPublicDescadastroRouteImport.update({
  id: '/api/public/descadastro',
  path: '/api/public/descadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCampaignsWebhookRoute =
  ApiPublicCampaignsWebhookRouteImport.update({
    id: '/api/public/campaigns/webhook',
    path: '/api/public/campaigns/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEvolutionWebhookRoute =
  ApiPublicEvolutionWebhookRouteImport.update({
    id: '/api/public/evolution/webhook',
    path: '/api/public/evolution/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleCalendarCallbackRoute =
  ApiPublicGoogleCalendarCallbackRouteImport.update({
    id: '/api/public/google-calendar/callback',
    path: '/api/public/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaCallbackRoute = ApiPublicMetaCallbackRouteImport.update({
  id: '/api/public/meta/callback',
  path: '/api/public/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaSyncRoute = ApiPublicMetaSyncRouteImport.update({
  id: '/api/public/meta/sync',
  path: '/api/public/meta/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackingWebhookRoute =
  ApiPublicTrackingWebhookRouteImport.update({
    id: '/api/public/tracking/webhook',
    path: '/api/public/tracking/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/auth': typeof AuthRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atendimentos': typeof AuthenticatedAtendimentosRouteWithChildren
  '/autenticidade': typeof AuthenticatedAutenticidadeRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/cambio': typeof AuthenticatedCambioRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/chat': typeof AuthenticatedChatRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/disparador': typeof AuthenticatedDisparadorRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/equipe': typeof AuthenticatedEquipeRouteWithChildren
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fornecedor': typeof AuthenticatedFornecedorRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRouteWithChildren
  '/hierarquia': typeof AuthenticatedHierarquiaRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/promocoes': typeof AuthenticatedPromocoesRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/scripts': typeof AuthenticatedScriptsRouteWithChildren
  '/sistemas-divisionais': typeof AuthenticatedSistemasDivisionaisRoute
  '/tarefas': typeof AuthenticatedTarefasRouteWithChildren
  '/trafego-pago': typeof AuthenticatedTrafegoPagoRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/recibo/$token': typeof ReciboTokenRoute
  '/verificar/$batchId': typeof VerificarBatchIdRoute
  '/atendimentos/contas': typeof AuthenticatedAtendimentosContasRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/confirmar-entrega/$token': typeof AuthenticatedConfirmarEntregaTokenRoute
  '/contatos/mapa': typeof AuthenticatedContatosMapaRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/equipe/$id': typeof AuthenticatedEquipeIdRoute
  '/equipe/hierarquia': typeof AuthenticatedEquipeHierarquiaRoute
  '/fornecedores/$id': typeof AuthenticatedFornecedoresIdRoute
  '/scripts/$id': typeof AuthenticatedScriptsIdRoute
  '/tarefas/$id': typeof AuthenticatedTarefasIdRoute
  '/api/download/pdf': typeof ApiDownloadPdfRoute
  '/api/public/descadastro': typeof ApiPublicDescadastroRoute
  '/atendimentos/': typeof AuthenticatedAtendimentosIndexRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/equipe/': typeof AuthenticatedEquipeIndexRoute
  '/fornecedores/': typeof AuthenticatedFornecedoresIndexRoute
  '/api/public/campaigns/webhook': typeof ApiPublicCampaignsWebhookRoute
  '/api/public/evolution/webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
  '/api/public/meta/sync': typeof ApiPublicMetaSyncRoute
  '/api/public/tracking/webhook': typeof ApiPublicTrackingWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/auth': typeof AuthRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/autenticidade': typeof AuthenticatedAutenticidadeRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/cambio': typeof AuthenticatedCambioRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/chat': typeof AuthenticatedChatRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contatos': typeof AuthenticatedContatosRoute
  '/disparador': typeof AuthenticatedDisparadorRoute
  '/entregas': typeof AuthenticatedEntregasRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/fornecedor': typeof AuthenticatedFornecedorRoute
  '/hierarquia': typeof AuthenticatedHierarquiaRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/promocoes': typeof AuthenticatedPromocoesRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/scripts': typeof AuthenticatedScriptsRouteWithChildren
  '/sistemas-divisionais': typeof AuthenticatedSistemasDivisionaisRoute
  '/tarefas': typeof AuthenticatedTarefasRouteWithChildren
  '/trafego-pago': typeof AuthenticatedTrafegoPagoRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/recibo/$token': typeof ReciboTokenRoute
  '/verificar/$batchId': typeof VerificarBatchIdRoute
  '/atendimentos/contas': typeof AuthenticatedAtendimentosContasRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/confirmar-entrega/$token': typeof AuthenticatedConfirmarEntregaTokenRoute
  '/contatos/mapa': typeof AuthenticatedContatosMapaRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/equipe/$id': typeof AuthenticatedEquipeIdRoute
  '/equipe/hierarquia': typeof AuthenticatedEquipeHierarquiaRoute
  '/fornecedores/$id': typeof AuthenticatedFornecedoresIdRoute
  '/scripts/$id': typeof AuthenticatedScriptsIdRoute
  '/tarefas/$id': typeof AuthenticatedTarefasIdRoute
  '/api/download/pdf': typeof ApiDownloadPdfRoute
  '/api/public/descadastro': typeof ApiPublicDescadastroRoute
  '/atendimentos': typeof AuthenticatedAtendimentosIndexRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/equipe': typeof AuthenticatedEquipeIndexRoute
  '/fornecedores': typeof AuthenticatedFornecedoresIndexRoute
  '/api/public/campaigns/webhook': typeof ApiPublicCampaignsWebhookRoute
  '/api/public/evolution/webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
  '/api/public/meta/sync': typeof ApiPublicMetaSyncRoute
  '/api/public/tracking/webhook': typeof ApiPublicTrackingWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acesso-negado': typeof AcessoNegadoRoute
  '/auth': typeof AuthRoute
  '/_authenticated/acessos': typeof AuthenticatedAcessosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/atendimentos': typeof AuthenticatedAtendimentosRouteWithChildren
  '/_authenticated/autenticidade': typeof AuthenticatedAutenticidadeRoute
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/cambio': typeof AuthenticatedCambioRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contatos': typeof AuthenticatedContatosRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/disparador': typeof AuthenticatedDisparadorRoute
  '/_authenticated/entregas': typeof AuthenticatedEntregasRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRouteWithChildren
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/fornecedor': typeof AuthenticatedFornecedorRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRouteWithChildren
  '/_authenticated/hierarquia': typeof AuthenticatedHierarquiaRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/investimentos': typeof AuthenticatedInvestimentosRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/promocoes': typeof AuthenticatedPromocoesRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/scripts': typeof AuthenticatedScriptsRouteWithChildren
  '/_authenticated/sistemas-divisionais': typeof AuthenticatedSistemasDivisionaisRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRouteWithChildren
  '/_authenticated/trafego-pago': typeof AuthenticatedTrafegoPagoRoute
  '/catalogo/$slug': typeof CatalogoSlugRoute
  '/pedido/$token': typeof PedidoTokenRoute
  '/recibo/$token': typeof ReciboTokenRoute
  '/verificar/$batchId': typeof VerificarBatchIdRoute
  '/_authenticated/atendimentos/contas': typeof AuthenticatedAtendimentosContasRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/confirmar-entrega/$token': typeof AuthenticatedConfirmarEntregaTokenRoute
  '/_authenticated/contatos_/mapa': typeof AuthenticatedContatosMapaRoute
  '/_authenticated/crm/$id': typeof AuthenticatedCrmIdRoute
  '/_authenticated/equipe/$id': typeof AuthenticatedEquipeIdRoute
  '/_authenticated/equipe/hierarquia': typeof AuthenticatedEquipeHierarquiaRoute
  '/_authenticated/fornecedores/$id': typeof AuthenticatedFornecedoresIdRoute
  '/_authenticated/scripts/$id': typeof AuthenticatedScriptsIdRoute
  '/_authenticated/tarefas/$id': typeof AuthenticatedTarefasIdRoute
  '/api/download/pdf': typeof ApiDownloadPdfRoute
  '/api/public/descadastro': typeof ApiPublicDescadastroRoute
  '/_authenticated/atendimentos/': typeof AuthenticatedAtendimentosIndexRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/equipe/': typeof AuthenticatedEquipeIndexRoute
  '/_authenticated/fornecedores/': typeof AuthenticatedFornecedoresIndexRoute
  '/api/public/campaigns/webhook': typeof ApiPublicCampaignsWebhookRoute
  '/api/public/evolution/webhook': typeof ApiPublicEvolutionWebhookRoute
  '/api/public/google-calendar/callback': typeof ApiPublicGoogleCalendarCallbackRoute
  '/api/public/meta/callback': typeof ApiPublicMetaCallbackRoute
  '/api/public/meta/sync': typeof ApiPublicMetaSyncRoute
  '/api/public/tracking/webhook': typeof ApiPublicTrackingWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-negado'
    | '/auth'
    | '/acessos'
    | '/admin'
    | '/atendimentos'
    | '/autenticidade'
    | '/avisos'
    | '/biblioteca'
    | '/cambio'
    | '/categorias'
    | '/chat'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/contatos'
    | '/crm'
    | '/disparador'
    | '/entregas'
    | '/equipe'
    | '/estoque'
    | '/financeiro'
    | '/fornecedor'
    | '/fornecedores'
    | '/hierarquia'
    | '/integracoes'
    | '/investimentos'
    | '/painel'
    | '/pedidos'
    | '/produtos'
    | '/promocoes'
    | '/ranking'
    | '/relatorios'
    | '/scripts'
    | '/sistemas-divisionais'
    | '/tarefas'
    | '/trafego-pago'
    | '/catalogo/$slug'
    | '/pedido/$token'
    | '/recibo/$token'
    | '/verificar/$batchId'
    | '/atendimentos/contas'
    | '/clientes/$id'
    | '/confirmar-entrega/$token'
    | '/contatos/mapa'
    | '/crm/$id'
    | '/equipe/$id'
    | '/equipe/hierarquia'
    | '/fornecedores/$id'
    | '/scripts/$id'
    | '/tarefas/$id'
    | '/api/download/pdf'
    | '/api/public/descadastro'
    | '/atendimentos/'
    | '/crm/'
    | '/equipe/'
    | '/fornecedores/'
    | '/api/public/campaigns/webhook'
    | '/api/public/evolution/webhook'
    | '/api/public/google-calendar/callback'
    | '/api/public/meta/callback'
    | '/api/public/meta/sync'
    | '/api/public/tracking/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-negado'
    | '/auth'
    | '/acessos'
    | '/admin'
    | '/autenticidade'
    | '/avisos'
    | '/biblioteca'
    | '/cambio'
    | '/categorias'
    | '/chat'
    | '/clientes'
    | '/compras'
    | '/configuracoes'
    | '/contatos'
    | '/disparador'
    | '/entregas'
    | '/estoque'
    | '/financeiro'
    | '/fornecedor'
    | '/hierarquia'
    | '/integracoes'
    | '/investimentos'
    | '/painel'
    | '/pedidos'
    | '/produtos'
    | '/promocoes'
    | '/ranking'
    | '/relatorios'
    | '/scripts'
    | '/sistemas-divisionais'
    | '/tarefas'
    | '/trafego-pago'
    | '/catalogo/$slug'
    | '/pedido/$token'
    | '/recibo/$token'
    | '/verificar/$batchId'
    | '/atendimentos/contas'
    | '/clientes/$id'
    | '/confirmar-entrega/$token'
    | '/contatos/mapa'
    | '/crm/$id'
    | '/equipe/$id'
    | '/equipe/hierarquia'
    | '/fornecedores/$id'
    | '/scripts/$id'
    | '/tarefas/$id'
    | '/api/download/pdf'
    | '/api/public/descadastro'
    | '/atendimentos'
    | '/crm'
    | '/equipe'
    | '/fornecedores'
    | '/api/public/campaigns/webhook'
    | '/api/public/evolution/webhook'
    | '/api/public/google-calendar/callback'
    | '/api/public/meta/callback'
    | '/api/public/meta/sync'
    | '/api/public/tracking/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acesso-negado'
    | '/auth'
    | '/_authenticated/acessos'
    | '/_authenticated/admin'
    | '/_authenticated/atendimentos'
    | '/_authenticated/autenticidade'
    | '/_authenticated/avisos'
    | '/_authenticated/biblioteca'
    | '/_authenticated/cambio'
    | '/_authenticated/categorias'
    | '/_authenticated/chat'
    | '/_authenticated/clientes'
    | '/_authenticated/compras'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contatos'
    | '/_authenticated/crm'
    | '/_authenticated/disparador'
    | '/_authenticated/entregas'
    | '/_authenticated/equipe'
    | '/_authenticated/estoque'
    | '/_authenticated/financeiro'
    | '/_authenticated/fornecedor'
    | '/_authenticated/fornecedores'
    | '/_authenticated/hierarquia'
    | '/_authenticated/integracoes'
    | '/_authenticated/investimentos'
    | '/_authenticated/painel'
    | '/_authenticated/pedidos'
    | '/_authenticated/produtos'
    | '/_authenticated/promocoes'
    | '/_authenticated/ranking'
    | '/_authenticated/relatorios'
    | '/_authenticated/scripts'
    | '/_authenticated/sistemas-divisionais'
    | '/_authenticated/tarefas'
    | '/_authenticated/trafego-pago'
    | '/catalogo/$slug'
    | '/pedido/$token'
    | '/recibo/$token'
    | '/verificar/$batchId'
    | '/_authenticated/atendimentos/contas'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/confirmar-entrega/$token'
    | '/_authenticated/contatos_/mapa'
    | '/_authenticated/crm/$id'
    | '/_authenticated/equipe/$id'
    | '/_authenticated/equipe/hierarquia'
    | '/_authenticated/fornecedores/$id'
    | '/_authenticated/scripts/$id'
    | '/_authenticated/tarefas/$id'
    | '/api/download/pdf'
    | '/api/public/descadastro'
    | '/_authenticated/atendimentos/'
    | '/_authenticated/crm/'
    | '/_authenticated/equipe/'
    | '/_authenticated/fornecedores/'
    | '/api/public/campaigns/webhook'
    | '/api/public/evolution/webhook'
    | '/api/public/google-calendar/callback'
    | '/api/public/meta/callback'
    | '/api/public/meta/sync'
    | '/api/public/tracking/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  AuthRoute: typeof AuthRoute
  CatalogoSlugRoute: typeof CatalogoSlugRoute
  PedidoTokenRoute: typeof PedidoTokenRoute
  ReciboTokenRoute: typeof ReciboTokenRoute
  VerificarBatchIdRoute: typeof VerificarBatchIdRoute
  ApiDownloadPdfRoute: typeof ApiDownloadPdfRoute
  ApiPublicDescadastroRoute: typeof ApiPublicDescadastroRoute
  ApiPublicCampaignsWebhookRoute: typeof ApiPublicCampaignsWebhookRoute
  ApiPublicEvolutionWebhookRoute: typeof ApiPublicEvolutionWebhookRoute
  ApiPublicGoogleCalendarCallbackRoute: typeof ApiPublicGoogleCalendarCallbackRoute
  ApiPublicMetaCallbackRoute: typeof ApiPublicMetaCallbackRoute
  ApiPublicMetaSyncRoute: typeof ApiPublicMetaSyncRoute
  ApiPublicTrackingWebhookRoute: typeof ApiPublicTrackingWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/acessos': {
      id: '/_authenticated/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AuthenticatedAcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atendimentos': {
      id: '/_authenticated/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AuthenticatedAtendimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autenticidade': {
      id: '/_authenticated/autenticidade'
      path: '/autenticidade'
      fullPath: '/autenticidade'
      preLoaderRoute: typeof AuthenticatedAutenticidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cambio': {
      id: '/_authenticated/cambio'
      path: '/cambio'
      fullPath: '/cambio'
      preLoaderRoute: typeof AuthenticatedCambioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos': {
      id: '/_authenticated/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AuthenticatedContatosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disparador': {
      id: '/_authenticated/disparador'
      path: '/disparador'
      fullPath: '/disparador'
      preLoaderRoute: typeof AuthenticatedDisparadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregas': {
      id: '/_authenticated/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AuthenticatedEntregasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedor': {
      id: '/_authenticated/fornecedor'
      path: '/fornecedor'
      fullPath: '/fornecedor'
      preLoaderRoute: typeof AuthenticatedFornecedorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hierarquia': {
      id: '/_authenticated/hierarquia'
      path: '/hierarquia'
      fullPath: '/hierarquia'
      preLoaderRoute: typeof AuthenticatedHierarquiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investimentos': {
      id: '/_authenticated/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof AuthenticatedInvestimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promocoes': {
      id: '/_authenticated/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof AuthenticatedPromocoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scripts': {
      id: '/_authenticated/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof AuthenticatedScriptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sistemas-divisionais': {
      id: '/_authenticated/sistemas-divisionais'
      path: '/sistemas-divisionais'
      fullPath: '/sistemas-divisionais'
      preLoaderRoute: typeof AuthenticatedSistemasDivisionaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trafego-pago': {
      id: '/_authenticated/trafego-pago'
      path: '/trafego-pago'
      fullPath: '/trafego-pago'
      preLoaderRoute: typeof AuthenticatedTrafegoPagoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/catalogo/$slug': {
      id: '/catalogo/$slug'
      path: '/catalogo/$slug'
      fullPath: '/catalogo/$slug'
      preLoaderRoute: typeof CatalogoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$token': {
      id: '/pedido/$token'
      path: '/pedido/$token'
      fullPath: '/pedido/$token'
      preLoaderRoute: typeof PedidoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recibo/$token': {
      id: '/recibo/$token'
      path: '/recibo/$token'
      fullPath: '/recibo/$token'
      preLoaderRoute: typeof ReciboTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificar/$batchId': {
      id: '/verificar/$batchId'
      path: '/verificar/$batchId'
      fullPath: '/verificar/$batchId'
      preLoaderRoute: typeof VerificarBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atendimentos/': {
      id: '/_authenticated/atendimentos/'
      path: '/'
      fullPath: '/atendimentos/'
      preLoaderRoute: typeof AuthenticatedAtendimentosIndexRouteImport
      parentRoute: typeof AuthenticatedAtendimentosRoute
    }
    '/_authenticated/atendimentos/contas': {
      id: '/_authenticated/atendimentos/contas'
      path: '/contas'
      fullPath: '/atendimentos/contas'
      preLoaderRoute: typeof AuthenticatedAtendimentosContasRouteImport
      parentRoute: typeof AuthenticatedAtendimentosRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/confirmar-entrega/$token': {
      id: '/_authenticated/confirmar-entrega/$token'
      path: '/confirmar-entrega/$token'
      fullPath: '/confirmar-entrega/$token'
      preLoaderRoute: typeof AuthenticatedConfirmarEntregaTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contatos_/mapa': {
      id: '/_authenticated/contatos_/mapa'
      path: '/contatos/mapa'
      fullPath: '/contatos/mapa'
      preLoaderRoute: typeof AuthenticatedContatosMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/$id': {
      id: '/_authenticated/crm/$id'
      path: '/$id'
      fullPath: '/crm/$id'
      preLoaderRoute: typeof AuthenticatedCrmIdRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/equipe/': {
      id: '/_authenticated/equipe/'
      path: '/'
      fullPath: '/equipe/'
      preLoaderRoute: typeof AuthenticatedEquipeIndexRouteImport
      parentRoute: typeof AuthenticatedEquipeRoute
    }
    '/_authenticated/equipe/$id': {
      id: '/_authenticated/equipe/$id'
      path: '/$id'
      fullPath: '/equipe/$id'
      preLoaderRoute: typeof AuthenticatedEquipeIdRouteImport
      parentRoute: typeof AuthenticatedEquipeRoute
    }
    '/_authenticated/equipe/hierarquia': {
      id: '/_authenticated/equipe/hierarquia'
      path: '/hierarquia'
      fullPath: '/equipe/hierarquia'
      preLoaderRoute: typeof AuthenticatedEquipeHierarquiaRouteImport
      parentRoute: typeof AuthenticatedEquipeRoute
    }
    '/_authenticated/fornecedores/': {
      id: '/_authenticated/fornecedores/'
      path: '/'
      fullPath: '/fornecedores/'
      preLoaderRoute: typeof AuthenticatedFornecedoresIndexRouteImport
      parentRoute: typeof AuthenticatedFornecedoresRoute
    }
    '/_authenticated/fornecedores/$id': {
      id: '/_authenticated/fornecedores/$id'
      path: '/$id'
      fullPath: '/fornecedores/$id'
      preLoaderRoute: typeof AuthenticatedFornecedoresIdRouteImport
      parentRoute: typeof AuthenticatedFornecedoresRoute
    }
    '/_authenticated/scripts/$id': {
      id: '/_authenticated/scripts/$id'
      path: '/$id'
      fullPath: '/scripts/$id'
      preLoaderRoute: typeof AuthenticatedScriptsIdRouteImport
      parentRoute: typeof AuthenticatedScriptsRoute
    }
    '/_authenticated/tarefas/$id': {
      id: '/_authenticated/tarefas/$id'
      path: '/$id'
      fullPath: '/tarefas/$id'
      preLoaderRoute: typeof AuthenticatedTarefasIdRouteImport
      parentRoute: typeof AuthenticatedTarefasRoute
    }
    '/api/download/pdf': {
      id: '/api/download/pdf'
      path: '/api/download/pdf'
      fullPath: '/api/download/pdf'
      preLoaderRoute: typeof ApiDownloadPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/descadastro': {
      id: '/api/public/descadastro'
      path: '/api/public/descadastro'
      fullPath: '/api/public/descadastro'
      preLoaderRoute: typeof ApiPublicDescadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/campaigns/webhook': {
      id: '/api/public/campaigns/webhook'
      path: '/api/public/campaigns/webhook'
      fullPath: '/api/public/campaigns/webhook'
      preLoaderRoute: typeof ApiPublicCampaignsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/evolution/webhook': {
      id: '/api/public/evolution/webhook'
      path: '/api/public/evolution/webhook'
      fullPath: '/api/public/evolution/webhook'
      preLoaderRoute: typeof ApiPublicEvolutionWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-calendar/callback': {
      id: '/api/public/google-calendar/callback'
      path: '/api/public/google-calendar/callback'
      fullPath: '/api/public/google-calendar/callback'
      preLoaderRoute: typeof ApiPublicGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/callback': {
      id: '/api/public/meta/callback'
      path: '/api/public/meta/callback'
      fullPath: '/api/public/meta/callback'
      preLoaderRoute: typeof ApiPublicMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/sync': {
      id: '/api/public/meta/sync'
      path: '/api/public/meta/sync'
      fullPath: '/api/public/meta/sync'
      preLoaderRoute: typeof ApiPublicMetaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tracking/webhook': {
      id: '/api/public/tracking/webhook'
      path: '/api/public/tracking/webhook'
      fullPath: '/api/public/tracking/webhook'
      preLoaderRoute: typeof ApiPublicTrackingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAtendimentosRouteChildren {
  AuthenticatedAtendimentosContasRoute: typeof AuthenticatedAtendimentosContasRoute
  AuthenticatedAtendimentosIndexRoute: typeof AuthenticatedAtendimentosIndexRoute
}

const AuthenticatedAtendimentosRouteChildren: AuthenticatedAtendimentosRouteChildren =
  {
    AuthenticatedAtendimentosContasRoute: AuthenticatedAtendimentosContasRoute,
    AuthenticatedAtendimentosIndexRoute: AuthenticatedAtendimentosIndexRoute,
  }

const AuthenticatedAtendimentosRouteWithChildren =
  AuthenticatedAtendimentosRoute._addFileChildren(
    AuthenticatedAtendimentosRouteChildren,
  )

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmIdRoute: typeof AuthenticatedCrmIdRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmIdRoute: AuthenticatedCrmIdRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedEquipeRouteChildren {
  AuthenticatedEquipeIdRoute: typeof AuthenticatedEquipeIdRoute
  AuthenticatedEquipeHierarquiaRoute: typeof AuthenticatedEquipeHierarquiaRoute
  AuthenticatedEquipeIndexRoute: typeof AuthenticatedEquipeIndexRoute
}

const AuthenticatedEquipeRouteChildren: AuthenticatedEquipeRouteChildren = {
  AuthenticatedEquipeIdRoute: AuthenticatedEquipeIdRoute,
  AuthenticatedEquipeHierarquiaRoute: AuthenticatedEquipeHierarquiaRoute,
  AuthenticatedEquipeIndexRoute: AuthenticatedEquipeIndexRoute,
}

const AuthenticatedEquipeRouteWithChildren =
  AuthenticatedEquipeRoute._addFileChildren(AuthenticatedEquipeRouteChildren)

interface AuthenticatedFornecedoresRouteChildren {
  AuthenticatedFornecedoresIdRoute: typeof AuthenticatedFornecedoresIdRoute
  AuthenticatedFornecedoresIndexRoute: typeof AuthenticatedFornecedoresIndexRoute
}

const AuthenticatedFornecedoresRouteChildren: AuthenticatedFornecedoresRouteChildren =
  {
    AuthenticatedFornecedoresIdRoute: AuthenticatedFornecedoresIdRoute,
    AuthenticatedFornecedoresIndexRoute: AuthenticatedFornecedoresIndexRoute,
  }

const AuthenticatedFornecedoresRouteWithChildren =
  AuthenticatedFornecedoresRoute._addFileChildren(
    AuthenticatedFornecedoresRouteChildren,
  )

interface AuthenticatedScriptsRouteChildren {
  AuthenticatedScriptsIdRoute: typeof AuthenticatedScriptsIdRoute
}

const AuthenticatedScriptsRouteChildren: AuthenticatedScriptsRouteChildren = {
  AuthenticatedScriptsIdRoute: AuthenticatedScriptsIdRoute,
}

const AuthenticatedScriptsRouteWithChildren =
  AuthenticatedScriptsRoute._addFileChildren(AuthenticatedScriptsRouteChildren)

interface AuthenticatedTarefasRouteChildren {
  AuthenticatedTarefasIdRoute: typeof AuthenticatedTarefasIdRoute
}

const AuthenticatedTarefasRouteChildren: AuthenticatedTarefasRouteChildren = {
  AuthenticatedTarefasIdRoute: AuthenticatedTarefasIdRoute,
}

const AuthenticatedTarefasRouteWithChildren =
  AuthenticatedTarefasRoute._addFileChildren(AuthenticatedTarefasRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcessosRoute: typeof AuthenticatedAcessosRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAtendimentosRoute: typeof AuthenticatedAtendimentosRouteWithChildren
  AuthenticatedAutenticidadeRoute: typeof AuthenticatedAutenticidadeRoute
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedCambioRoute: typeof AuthenticatedCambioRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContatosRoute: typeof AuthenticatedContatosRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedDisparadorRoute: typeof AuthenticatedDisparadorRoute
  AuthenticatedEntregasRoute: typeof AuthenticatedEntregasRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRouteWithChildren
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedFornecedorRoute: typeof AuthenticatedFornecedorRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRouteWithChildren
  AuthenticatedHierarquiaRoute: typeof AuthenticatedHierarquiaRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedInvestimentosRoute: typeof AuthenticatedInvestimentosRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedPromocoesRoute: typeof AuthenticatedPromocoesRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedScriptsRoute: typeof AuthenticatedScriptsRouteWithChildren
  AuthenticatedSistemasDivisionaisRoute: typeof AuthenticatedSistemasDivisionaisRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRouteWithChildren
  AuthenticatedTrafegoPagoRoute: typeof AuthenticatedTrafegoPagoRoute
  AuthenticatedConfirmarEntregaTokenRoute: typeof AuthenticatedConfirmarEntregaTokenRoute
  AuthenticatedContatosMapaRoute: typeof AuthenticatedContatosMapaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcessosRoute: AuthenticatedAcessosRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAtendimentosRoute: AuthenticatedAtendimentosRouteWithChildren,
  AuthenticatedAutenticidadeRoute: AuthenticatedAutenticidadeRoute,
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedCambioRoute: AuthenticatedCambioRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContatosRoute: AuthenticatedContatosRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedDisparadorRoute: AuthenticatedDisparadorRoute,
  AuthenticatedEntregasRoute: AuthenticatedEntregasRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRouteWithChildren,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedFornecedorRoute: AuthenticatedFornecedorRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRouteWithChildren,
  AuthenticatedHierarquiaRoute: AuthenticatedHierarquiaRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedInvestimentosRoute: AuthenticatedInvestimentosRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedPromocoesRoute: AuthenticatedPromocoesRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedScriptsRoute: AuthenticatedScriptsRouteWithChildren,
  AuthenticatedSistemasDivisionaisRoute: AuthenticatedSistemasDivisionaisRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRouteWithChildren,
  AuthenticatedTrafegoPagoRoute: AuthenticatedTrafegoPagoRoute,
  AuthenticatedConfirmarEntregaTokenRoute:
    AuthenticatedConfirmarEntregaTokenRoute,
  AuthenticatedContatosMapaRoute: AuthenticatedContatosMapaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcessoNegadoRoute: AcessoNegadoRoute,
  AuthRoute: AuthRoute,
  CatalogoSlugRoute: CatalogoSlugRoute,
  PedidoTokenRoute: PedidoTokenRoute,
  ReciboTokenRoute: ReciboTokenRoute,
  VerificarBatchIdRoute: VerificarBatchIdRoute,
  ApiDownloadPdfRoute: ApiDownloadPdfRoute,
  ApiPublicDescadastroRoute: ApiPublicDescadastroRoute,
  ApiPublicCampaignsWebhookRoute: ApiPublicCampaignsWebhookRoute,
  ApiPublicEvolutionWebhookRoute: ApiPublicEvolutionWebhookRoute,
  ApiPublicGoogleCalendarCallbackRoute: ApiPublicGoogleCalendarCallbackRoute,
  ApiPublicMetaCallbackRoute: ApiPublicMetaCallbackRoute,
  ApiPublicMetaSyncRoute: ApiPublicMetaSyncRoute,
  ApiPublicTrackingWebhookRoute: ApiPublicTrackingWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
